# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.132.0+1.21.8

# Mod Properties
mod_version=0.1.0+1.20.1
maven_group=net.mysticforge
archives_base_name=QuellCraft

# Cardinal Components Version
cca_version = 7.0.0-beta.1

# Accessories Version
accessories_version = 1.3.4-beta+1.21.8
owo_version = 0.12.22+1.21.8

# Geckolib5 Version
geckolib_version=5.2.2